build:
  image: docker:19.03.12
  variables:
    CI_REGISTRY_USER: mcgonagle
    CI_REGISTRY_PASSWORD: glpat-TNCRR6uZEm4jfqZsKT4x
    CI_REGISTRY: registry.gitlab.com
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/sa-demo-group/thomas-mcgonagle-demo-group/liveterm .
    - docker push $CI_REGISTRY/sa-demo-group/thomas-mcgonagle-demo-group/liveterm
deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl apply -f 