build:
  image: docker:19.03.12
  variables:
    CI_REGISTRY_USER: "$CI_REGISTRY_USER"
    CI_REGISTRY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    CI_REGISTRY: "$CI_REGISTRY"
  stage: build
  services:
  - docker:19.03.12-dind
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY/sa-demo-group/thomas-mcgonagle-demo-group/liveterm
    .
  - docker push $CI_REGISTRY/sa-demo-group/thomas-mcgonagle-demo-group/liveterm
deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint:
    - ''
  script:
  - kubectl config get-contexts
  - kubectl config use-context sa-demo-group/thomas-mcgonagle-demo-group/LiveTerm:liveterm
  - kubectl get pods
  - kubectl apply -f /builds/sa-demo-group/thomas-mcgonagle-demo-group/LiveTerm/kubernetes/liveterm-claim0-persistentvolumeclaim.yaml
  - kubectl apply -f /builds/sa-demo-group/thomas-mcgonagle-demo-group/LiveTerm/kubernetes/liveterm-deployment.yaml
  - kubectl apply -f /builds/sa-demo-group/thomas-mcgonagle-demo-group/LiveTerm/kubernetes/liveterm-service.yaml
  - kubectl get pods
