apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: liveterm
  name: liveterm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: liveterm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: liveterm
    spec:
      containers:
        - args:
            - npm
            - run
            - dev
          image: registry.gitlab.com/sa-demo-group/thomas-mcgonagle-demo-group/liveterm:latest 
          name: liveterm
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
      volumes:
        - name: liveterm-claim0
          persistentVolumeClaim:
            claimName: liveterm-claim0
status: {}
